### ISSUE TITLE
problems with __oldData__ and updated deps

### ISSUE THREAD

**Issue by kachkaev** [romseguy/d3-state-visualizer#10]
I originally discovered this problem in https://github.com/romseguy/redux-devtools-chart-monitor/issues/16, but also could reproduce it outside `redux-devtools-chart-monitor` (see https://github.com/romseguy/d3-state-visualizer/pull/9).

Looks like the source of the problem [in `src/charts/tree/tree.js`](https://github.com/romseguy/d3-state-visualizer/search?utf8=%E2%9C%93&q=__oldData__). I'd specifically blame [`this.__oldData__`](https://github.com/romseguy/d3-state-visualizer/blob/cb533bf79fc7fac993c80a677e4cf3aa8f9f49f7/src/charts/tree/tree.js#L253).

**Comment by zalmoxisus** [comment]
Should be related to my changes in https://github.com/romseguy/d3-state-visualizer/pull/6, though I didn't get this problem.

You could try to add a check if `this` exists [here](https://github.com/romseguy/d3-state-visualizer/blob/cb533bf79fc7fac993c80a677e4cf3aa8f9f49f7/src/charts/tree/tree.js#L253):
```js
return !!this && (!this.__oldData__ || d.value !== this.__oldData__.value)
```

If the node updates are shown, we can go with solution.

**Comment by kachkaev** [comment]
Hmmm...

I changed this in `node_modules/d3-state-visualiser/lib/charts/tree/tree.js` like this:

```js
        console.log('checking this', _this);
        return !!_this && (!_this.__oldData__ || d.value !== _this.__oldData__.value);
```
(there is `_this` instead of `this` because the code is traspiled).

The result of `console.log` is `undefined` in all cases. `_this` is declared here:
```
    function update(source) {
      var _this = this;
```
Shouldn't that function be bound to smth specific?

```js
    update.call(/* ??? */, data);
```

Feel free to try out the boilerplate from https://github.com/romseguy/d3-state-visualizer/pull/9

**Comment by romseguy** [comment]
From d3 docs: https://github.com/d3/d3-selection#selection_filter

> If a function, it is evaluated for each selected element, in order, being passed the current datum (d), the current index (i), and the current group (nodes), with `this` as the current DOM element.

Because of the arrow function getting transpiled, `this` is bound to `this` from parent scope i.e `undefined` instead of the DOM element  https://github.com/romseguy/d3-state-visualizer/blob/master/src/charts/tree/tree.js#L248

That fixes the error but not the blinking, will investigate later (or feel free to do so, thanks guys btw).

**Comment by zalmoxisus** [comment]
Good catch. That was changed [here](https://github.com/romseguy/d3-state-visualizer/commit/cb533bf79fc7fac993c80a677e4cf3aa8f9f49f7#diff-c9e69f2ad145e1cf67f4c0f430280b4bR248), that's why I wasn't getting any troubles before.

Regarding blinking, I guess it's because D3@4 is way different from D3@3. A quick fix would be to revert to version 3 and to revert https://github.com/romseguy/d3-state-visualizer/commit/cb533bf79fc7fac993c80a677e4cf3aa8f9f49f7#diff-c9e69f2ad145e1cf67f4c0f430280b4bR248. Though updating to 4 would be great.

**Comment by kachkaev** [comment]
I replaced the way the function was called and downgraded d3:
```patch
diff --git a/package.json b/package.json
index 4505a04..6d59e8a 100644
--- a/package.json
+++ b/package.json
@@ -52,7 +52,7 @@
   },
   "peerDependencies": {},
   "dependencies": {
-    "d3": "^3.5.6",
+    "d3": "~3.5.6",
     "d3tooltip": "^1.2.2",
     "deepmerge": "^0.2.10",
     "is-plain-object": "2.0.1",
diff --git a/src/charts/tree/tree.js b/src/charts/tree/tree.js
index 9b376c9..08fb377 100644
--- a/src/charts/tree/tree.js
+++ b/src/charts/tree/tree.js
@@ -245,7 +245,7 @@ export default function(DOMNode, options = {}) {
       nodeUpdate.select('circle').attr('r', 7)

       // blink updated nodes
-      nodeUpdate.filter(d => {
+      nodeUpdate.filter(function filter(d) {
         // test whether the relevant properties of d match
         // the equivalent property of the oldData
         // also test whether the old data exists,
```

However, this did not bring the plugin back to work:

![node-misplacement](https://cloud.githubusercontent.com/assets/608862/20625155/624b94be-b309-11e6-983f-f1502d4b96e1.PNG)

When I click on that bunch of nodes, they go back to where they should be, but when I toggle a node next time, some of the nodes gather in one spot again. Looks like the position is not being set up correctly on `enter`.

![node-misplacement-2](https://cloud.githubusercontent.com/assets/608862/20625187/8ca34644-b309-11e6-9630-01293144016a.PNG)

**Comment by kachkaev** [comment]
Could you guys have a look at the solution please? Redux chart monitor with this visualizer [is being downloaded 3.5K times per month](https://www.npmjs.com/package/redux-devtools-chart-monitor) plus it's also a part of the devtools extension (which might get in trouble when rebuilt next time).

__UPD:__ Ah, you're the same people as those who maintain that :laughing:

**Comment by zalmoxisus** [comment]
@kachkaev for some reason I cannot get the boilerplate branch working after checkout from upstream. `npm install` gives `Error: ENOENT: no such file or directory, uv_cwd`.

But in the master branch there are examples already and #11 fixes them. It works now with Redux DevTools as well.
