### ISSUE TITLE
Dealing with variable-depth state trees

### ISSUE THREAD

**Issue by Enet4** [romseguy/d3-state-visualizer#4]
One of my projects' state model contains a node tree of variable depth, representing a complex query. I have been trying to expand it in the visualizer, but to no avail. It simply shows `children[i]` nodes after 3 levels in.

![screenshot_2016-01-27_19-13-13](https://cloud.githubusercontent.com/assets/4738426/12625486/fbcf8fcc-c52b-11e5-8164-e7678391e50c.png)

I also don't think I can define a tree structure, because of its recursive definition.
Is there currently a way to achieve this without making other parts of the state expand, or this has to be implemented?

**Comment by romseguy** [comment]
The [map2tree](https://github.com/romseguy/map2tree/blob/master/src/index.js) function was written in a way that stops traversing the map on the first array. This was to cover the more common use case of storing _flat_ collections into a Redux store. An arbitrary depth of nested objects will be traversed, but nested collections won't.

In your example:

``` javascript
{
  query: {
    children: [
      {
        children: [ // this array won't be traversed!
        ]
      }
    ]
  }
}
```

**Comment by Enet4** [comment]
I see. I have now mapped the state with a conversion of arrays into objects. It's working better now, although being able to state which parts are to be expanded by default would have been a plus. :+1:
